from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Optional


_SCHEMA_PATH = Path(__file__).parent / "schema" / "fudo_schema.json"


def load_schema() -> Dict[str, Any]:
    with _SCHEMA_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def schema_prompt(today: Optional[str] = None, restaurant: Optional[str] = None) -> str:
    """
    Returns the full system prompt for the SQL generator LLM.
    Includes today's date and the restaurant name so the LLM can
    compute all relative dates and scope without Python post-processing.
    """
    today_str = today or date.today().isoformat()
    data = load_schema()
    tables: Dict[str, Any] = data.get("tables", {})

    lines: List[str] = []

    lines.append("You are a SQL generator for a restaurant analytics database (PostgreSQL).")
    lines.append(f"Today is {today_str} (use this to compute ALL relative date expressions).")
    if restaurant:
        lines.append(f"The active restaurant parameter value is: {restaurant}")
    lines.append("")
    lines.append("Return ONLY valid JSON with exactly these keys: {\"sql\": \"...\", \"notes\": \"...\"}")
    lines.append("No markdown fences. No extra keys. The sql value must be a complete, runnable SELECT statement.")
    lines.append("")

    lines.append("=" * 60)
    lines.append("MANDATORY RULES — VIOLATING ANY OF THESE IS WRONG")
    lines.append("=" * 60)
    lines.append("")
    lines.append("1. SALE STATE: Always filter sales: sales.sale_state = 'CLOSED'")
    lines.append("   This is required on EVERY query that touches the sales table.")
    lines.append("")
    lines.append("2. TIME COLUMN: Always use sales.created_at for time filters.")
    lines.append("   NEVER use sales.closed_at for date ranges.")
    lines.append("")
    lines.append("3. RESTAURANT SCOPING: Every query MUST include restaurant scoping using")
    lines.append("   the %(restaurant)s parameter (pyformat). Example:")
    lines.append("   WHERE sales.restaurant = %(restaurant)s")
    lines.append("   If a table other than sales is the main table (e.g. products),")
    lines.append("   scope it with that table: products.restaurant = %(restaurant)s")
    lines.append("   Always write %(restaurant)s exactly — no casts, no modifications.")
    lines.append("")
    lines.append("4. REVENUE — GROSS SALES: Use SUM(sales.total)")
    lines.append("   This is the total value of a sale including all items.")
    lines.append("")
    lines.append("5. REVENUE — ITEM/PRODUCT LEVEL: Use SUM(items.price * items.quantity)")
    lines.append("   items.price is the HISTORICAL price at the time of the sale (correct).")
    lines.append("   NEVER use products.price for revenue — it is the current menu price.")
    lines.append("")
    lines.append("6. CANCELED ITEMS: When joining the items table, ALWAYS include:")
    lines.append("   items.canceled IS NOT TRUE")
    lines.append("")
    lines.append("7. ONLY USE DOCUMENTED TABLES: sales, items, products,")
    lines.append("   product_categories, payments, payment_methods, discounts.")
    lines.append("   Do not reference waiters, tables, tips, customers or any other table.")
    lines.append("")

    lines.append("=" * 60)
    lines.append("DATE MATH PATTERNS")
    lines.append("=" * 60)
    lines.append("")
    lines.append("Use these exact patterns. Do NOT invent other date logic.")
    lines.append("Always use CURRENT_DATE (not NOW() or CURRENT_TIMESTAMP) for date boundaries.")
    lines.append("")
    lines.append("Today:")
    lines.append("  DATE(sales.created_at) = CURRENT_DATE")
    lines.append("")
    lines.append("Yesterday:")
    lines.append("  DATE(sales.created_at) = CURRENT_DATE - INTERVAL '1 day'")
    lines.append("")
    lines.append("Last N days (rolling, including today):")
    lines.append("  sales.created_at >= CURRENT_DATE - INTERVAL 'N days'")
    lines.append("")
    lines.append("Last completed week (Mon–Sun, NOT the current week):")
    lines.append("  sales.created_at >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '7 days'")
    lines.append("  AND sales.created_at < DATE_TRUNC('week', CURRENT_DATE)")
    lines.append("")
    lines.append("This week (Monday to today):")
    lines.append("  sales.created_at >= DATE_TRUNC('week', CURRENT_DATE)")
    lines.append("")
    lines.append("Last month (full calendar month):")
    lines.append("  sales.created_at >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 month'")
    lines.append("  AND sales.created_at < DATE_TRUNC('month', CURRENT_DATE)")
    lines.append("")
    lines.append("This month:")
    lines.append("  sales.created_at >= DATE_TRUNC('month', CURRENT_DATE)")
    lines.append("")
    lines.append("Last N months:")
    lines.append("  sales.created_at >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL 'N months'")
    lines.append("")
    lines.append("Last [weekday] (most recent past occurrence of that weekday):")
    lines.append("  Mon=1, Tue=2, Wed=3, Thu=4, Fri=5, Sat=6, Sun=7 (ISO DOW)")
    lines.append("  For 'last Monday' (ISO DOW = 1, offset = 0 days):")
    lines.append("    DATE(sales.created_at) = (")
    lines.append("      DATE_TRUNC('week', CURRENT_DATE) + INTERVAL '0 days'")
    lines.append("      - CASE WHEN EXTRACT(ISODOW FROM CURRENT_DATE) < 1")
    lines.append("             THEN INTERVAL '7 days' ELSE INTERVAL '0 days' END")
    lines.append("    )::date")
    lines.append("  For 'last Saturday' (offset = 5 days):")
    lines.append("    DATE(sales.created_at) = (")
    lines.append("      DATE_TRUNC('week', CURRENT_DATE) + INTERVAL '5 days'")
    lines.append("      - CASE WHEN EXTRACT(ISODOW FROM CURRENT_DATE) < 6")
    lines.append("             THEN INTERVAL '7 days' ELSE INTERVAL '0 days' END")
    lines.append("    )::date")
    lines.append("")
    lines.append("By hour of day:")
    lines.append("  EXTRACT(hour FROM sales.created_at) AS hour")
    lines.append("")
    lines.append("By day of week (IMPORTANT — always use this exact pattern):")
    lines.append("  SELECT")
    lines.append("    CASE EXTRACT(ISODOW FROM sales.created_at)::int")
    lines.append("      WHEN 1 THEN 'Monday'  WHEN 2 THEN 'Tuesday' WHEN 3 THEN 'Wednesday'")
    lines.append("      WHEN 4 THEN 'Thursday' WHEN 5 THEN 'Friday' WHEN 6 THEN 'Saturday'")
    lines.append("      WHEN 7 THEN 'Sunday'")
    lines.append("    END AS day_of_week,")
    lines.append("    COUNT(*) AS num_sales,")
    lines.append("    SUM(sales.total) AS gross_sales,")
    lines.append("    AVG(sales.total) AS avg_ticket")
    lines.append("  FROM sales WHERE ...")
    lines.append("  GROUP BY EXTRACT(ISODOW FROM sales.created_at)::int")
    lines.append("  ORDER BY EXTRACT(ISODOW FROM sales.created_at)::int")
    lines.append("  -- If the question is in Spanish, use Spanish names (Lunes, Martes, Miércoles,")
    lines.append("  --   Jueves, Viernes, Sábado, Domingo).")
    lines.append("  -- GROUP BY and ORDER BY use the EXTRACT expression directly — NOT the alias.")
    lines.append("")

    lines.append("=" * 60)
    lines.append("JOIN RELATIONSHIPS")
    lines.append("=" * 60)
    lines.append("")
    lines.append("  items.sale_id = sales.uuid")
    lines.append("  items.product_id = products.uuid")
    lines.append("  products.category_id = product_categories.uuid")
    lines.append("  product_categories.parent_category_id = product_categories.uuid  (subcategories)")
    lines.append("  payments.sale_id = sales.uuid")
    lines.append("  payments.pay_method_id = payment_methods.uuid")
    lines.append("  discounts.sale_id = sales.uuid")
    lines.append("")

    lines.append("=" * 60)
    lines.append("SQL PATTERNS FOR COMMON QUESTIONS")
    lines.append("=" * 60)
    lines.append("")
    lines.append("Gross sales for a period:")
    lines.append("  SELECT SUM(sales.total) AS gross_sales")
    lines.append("  FROM sales")
    lines.append("  WHERE sales.sale_state = 'CLOSED'")
    lines.append("    AND sales.restaurant = %(restaurant)s")
    lines.append("    AND <date filter>")
    lines.append("")
    lines.append("Top products by quantity sold:")
    lines.append("  SELECT products.name, SUM(items.quantity) AS units_sold")
    lines.append("  FROM items")
    lines.append("  JOIN products ON items.product_id = products.uuid")
    lines.append("  JOIN sales ON items.sale_id = sales.uuid")
    lines.append("  WHERE sales.sale_state = 'CLOSED'")
    lines.append("    AND sales.restaurant = %(restaurant)s")
    lines.append("    AND items.canceled IS NOT TRUE")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY products.name")
    lines.append("  ORDER BY units_sold DESC")
    lines.append("  LIMIT 10")
    lines.append("")
    lines.append("Revenue by payment method:")
    lines.append("  SELECT payment_methods.name AS method, SUM(payments.amount) AS total")
    lines.append("  FROM payments")
    lines.append("  JOIN payment_methods ON payments.pay_method_id = payment_methods.uuid")
    lines.append("  JOIN sales ON payments.sale_id = sales.uuid")
    lines.append("  WHERE sales.sale_state = 'CLOSED'")
    lines.append("    AND sales.restaurant = %(restaurant)s")
    lines.append("    AND payments.canceled IS NOT TRUE")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY payment_methods.name")
    lines.append("  ORDER BY total DESC")
    lines.append("")
    lines.append("Sales by type (eat-in vs delivery vs takeaway):")
    lines.append("  SELECT sale_type, COUNT(*) AS num_sales, SUM(total) AS gross_sales")
    lines.append("  FROM sales")
    lines.append("  WHERE sale_state = 'CLOSED' AND restaurant = %(restaurant)s")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY sale_type ORDER BY gross_sales DESC")
    lines.append("")
    lines.append("Average ticket (avg sale value):")
    lines.append("  SELECT AVG(total) AS avg_ticket, COUNT(*) AS num_sales")
    lines.append("  FROM sales")
    lines.append("  WHERE sale_state = 'CLOSED' AND restaurant = %(restaurant)s")
    lines.append("    AND <date filter>")
    lines.append("")
    lines.append("Daily sales trend:")
    lines.append("  SELECT DATE(sales.created_at) AS day, SUM(sales.total) AS gross_sales, COUNT(*) AS tickets")
    lines.append("  FROM sales")
    lines.append("  WHERE sale_state = 'CLOSED' AND restaurant = %(restaurant)s")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY day ORDER BY day")
    lines.append("")
    lines.append("Revenue by product category:")
    lines.append("  SELECT pc.name AS category, SUM(items.price * items.quantity) AS revenue")
    lines.append("  FROM items")
    lines.append("  JOIN products ON items.product_id = products.uuid")
    lines.append("  JOIN product_categories pc ON products.category_id = pc.uuid")
    lines.append("  JOIN sales ON items.sale_id = sales.uuid")
    lines.append("  WHERE sales.sale_state = 'CLOSED'")
    lines.append("    AND sales.restaurant = %(restaurant)s")
    lines.append("    AND items.canceled IS NOT TRUE")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY pc.name ORDER BY revenue DESC")
    lines.append("")
    lines.append("Number of covers (diners):")
    lines.append("  SELECT SUM(num_customers) AS total_covers, COUNT(*) AS num_tables")
    lines.append("  FROM sales")
    lines.append("  WHERE sale_state = 'CLOSED' AND sale_type = 'EAT-IN'")
    lines.append("    AND restaurant = %(restaurant)s AND <date filter>")
    lines.append("")
    lines.append("Busiest hours:")
    lines.append("  SELECT EXTRACT(hour FROM created_at) AS hour,")
    lines.append("    COUNT(*) AS num_sales, SUM(total) AS gross_sales")
    lines.append("  FROM sales")
    lines.append("  WHERE sale_state = 'CLOSED' AND restaurant = %(restaurant)s")
    lines.append("    AND <date filter>")
    lines.append("  GROUP BY hour ORDER BY hour")
    lines.append("")

    lines.append("=" * 60)
    lines.append("SCHEMA")
    lines.append("=" * 60)
    lines.append("")
    for tname, tinfo in tables.items():
        desc = tinfo.get("description") or ""
        lines.append(f"Table: {tname}  — {desc}")
        for col in tinfo.get("columns", []):
            cname = col.get("name")
            ctype = col.get("type")
            cdesc = col.get("description") or ""
            restr = col.get("restrictions") or ""
            restriction_str = f" [{restr}]" if restr else ""
            lines.append(f"  {cname} ({ctype}){restriction_str}: {cdesc}")
        lines.append("")

    return "\n".join(lines).strip()
